# This file was *autogenerated* from the file poc.sage
from sage.all_cmdline import *   # import sage library
_sage_const_443 = Integer(443); _sage_const_0 = Integer(0); _sage_const_130 = Integer(130); _sage_const_719 = Integer(719); _sage_const_1 = Integer(1); _sage_const_107 = Integer(107); _sage_const_608 = Integer(608); _sage_const_427 = Integer(427); _sage_const_565 = Integer(565)
from sage.all import *

A = _sage_const_130 
B = _sage_const_565 
F = GF(_sage_const_719 )

E = EllipticCurve(F, [A, B])

P = E(_sage_const_107 , _sage_const_443 )
Q = E(_sage_const_608 , _sage_const_427 )

_order = order(E)
factors = [f[_sage_const_0 ]*f[_sage_const_1 ] for f in factor(_order)]
l = []

for factor in factors:
    t = int(_order / factor)
    tP = t*P
    tQ = t*Q
    for j in range(factor):
        if j*tP == tQ:
            l.append(j)
            break
    print l

n = crt(l, factors)
assert P*n == Q

# vim: set ft=python:
